# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Service specific configuration
config:
  # <config-key>:
  #  env: <Environment variable for injection>
  #  value: ~ # null
  #       `~` means the value must be declared in configuration management system
  #       Best Practice : Set a value here only when the parameter is different between developers env and k8s ones
  #  public: true <optional>, indicates when the value is published on config map
  map-provider:
    env: CONFIG_KUBERNETES_MAP_PROVIDER
    value: ~
  widget-url:
    env: CONFIG_KUBERNETES_WIDGET_URL
    from: widget
  bridge-api-url:
    env: CONFIG_KUBERNETES_API_URL
    from: public-api

secret:
  api-key:
    env: CONFIG_KUBERNETES_API_KEY
    value: ~
  api-secret:
    env: CONFIG_KUBERNETES_API_SECRET
    value: ~
  map-api-key:
    env: CONFIG_KUBERNETES_MAP_API_KEY
    value: ~

image:
  repository: solocal/bridge-widget-demo

service:
  port: 8080

ingress:
  enabled: true
  hosts:
    # List of basename and public flag where this service will be exposed
    - basename: widget-demo

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  bo: {}
